/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_parcial2.pkg2;

import ConexionDAO.Conexion_Bueno;
import DTO.Datos_Bueno;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lecona
 */
public class JFPrincipal_Bueno extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal_Bueno
     */
    
    List<Datos_Bueno> listadatos_bueno = new ArrayList<Datos_Bueno>();
    String[] titulo = new String[]{"ID","Nombre","Telefono","Celular","Direccion"};
    DefaultTableModel mimodelo = new DefaultTableModel(null,titulo);
    String accion = "I";
    int valorID=0;
    
    public JFPrincipal_Bueno() {
        initComponents();
        btngrabar.setEnabled(false);
        //btncancelar.setEnabled(false);
        txtnombre.setEditable(false);
        txttelefono.setEditable(false);
        txtcelular.setEditable(false);
        txtdireccion.setEditable(false);
        CargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabladata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Celular", "Direccion"
            }
        ));
        tabladata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabladataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabladata);
        if (tabladata.getColumnModel().getColumnCount() > 0) {
            tabladata.getColumnModel().getColumn(0).setMinWidth(1);
            tabladata.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabladata.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Agenda");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Telefono");

        txtnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(102, 102, 102));

        txttelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Celular");

        txtcelular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtcelular.setForeground(new java.awt.Color(102, 102, 102));

        txtdireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(102, 102, 102));

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btngrabar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtdireccion))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btngrabar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btneditar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btneliminar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneditar)
                            .addComponent(btngrabar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneliminar)
                            .addComponent(btnagregar))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        txtnombre.setText("");
        txttelefono.setText("");
        txtcelular.setText("");
        txtdireccion.setText("");
        txtnombre.setEditable(true);
        txttelefono.setEditable(true);
        txtcelular.setEditable(true);
        txtdireccion.setEditable(true);
        btngrabar.setEnabled(true);
        accion="I";
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        // TODO add your handling code here:
        
        Conexion_Bueno conexion_bueno = new Conexion_Bueno();
        Datos_Bueno datos_bueno = new Datos_Bueno();
        datos_bueno.setNombre(txtnombre.getText());
        datos_bueno.setTelefono(Integer.valueOf(txttelefono.getText()));
        datos_bueno.setCelular(Integer.valueOf(txtcelular.getText()));
        datos_bueno.setDireccion(txtdireccion.getText());
        btngrabar.setText("Grabar");
        if (accion.equals("I")){
        if(conexion_bueno.insertar(datos_bueno)){
            JOptionPane.showMessageDialog(this, "Se grabo correctamente...");
        }else{
            JOptionPane.showMessageDialog(this, "Error al grabar...");
        }
        }else if (accion.equals("A")) {
            datos_bueno.setId(valorID);
            if(conexion_bueno.actualizar(datos_bueno)){
                JOptionPane.showMessageDialog(null, "Se actualizo correctamente","Actualizacion",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar","Actualizacion",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btngrabarActionPerformed
        CargarDatos();
    }
    
    
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        Conexion_Bueno conexion_bueno = new Conexion_Bueno();
        if (conexion_bueno.borrar(valorID)){
            JOptionPane.showMessageDialog(null, "Se elimino correctamente","Eliminar",JOptionPane.INFORMATION_MESSAGE);
        }else{
           JOptionPane.showMessageDialog(null, "Error al eliminar","Eliminar",JOptionPane.INFORMATION_MESSAGE);
        }
        CargarDatos();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        btneditar.setEnabled(false);
        //btneliminar.setEnabled(false);
        //btnnuevo.setEnabled(false);
        btngrabar.setEnabled(true);
        txtnombre.setEditable(true);
        txttelefono.setEditable(true);
        txtcelular.setEditable(true);
        txtdireccion.setEditable(true);
        //btncancelar.setEnabled(true);
        btngrabar.setText("Actualizar");
        accion ="A";
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void tabladataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladataMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se preciono algun lugar de la tabla","Seleccion",JOptionPane.INFORMATION_MESSAGE);
        int columna = tabladata.getSelectedColumn();
        int fila = tabladata.getSelectedRow();
        String cadena = tabladata.getValueAt(fila, columna).toString();
        JOptionPane.showMessageDialog(null, "Columna -> " + columna + "\n fila -> " + fila + "\n informacion en la celda -> " + cadena,"Posicion seleccionada ",JOptionPane.INFORMATION_MESSAGE);
        txtnombre.setText(tabladata.getValueAt(fila, 1).toString());
        txttelefono.setText(tabladata.getValueAt(fila, 2).toString());
        txtcelular.setText(tabladata.getValueAt(fila, 3).toString());
        txtdireccion.setText(tabladata.getValueAt(fila, 4).toString());
        valorID = Integer.valueOf(tabladata.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tabladataMousePressed

   
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal_Bueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal_Bueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal_Bueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal_Bueno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new JFPrincipal_Bueno().setVisible(true);
            }
        });
    }

   private void CargarDatos(){
       //Para limpiar el modelo
       mimodelo = new DefaultTableModel(null,titulo);
       //Para recargar la tabla cada vez que se modifique algo
       Conexion_Bueno conexion_bueno = new Conexion_Bueno();
        if (conexion_bueno.consultartodos()){
            listadatos_bueno = conexion_bueno.getListDatos_Bueno();
            for(Datos_Bueno datos_bueno : listadatos_bueno){
               mimodelo.addRow(new Object[]{String.valueOf(datos_bueno.getId()),datos_bueno.getNombre(),String.valueOf(datos_bueno.getTelefono()),String.valueOf(datos_bueno.getCelular()),datos_bueno.getDireccion()});
            }
            tabladata.setModel(mimodelo);
        } else {
            JOptionPane.showMessageDialog(this, "No se pueden cargar los datos....");
            
        }
   }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladata;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
